### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by carodelafuente** [Ray1016/Colmar-Academy#3]
You missed the semi-colon in this block and didn't put the width in a new line here: https://github.com/Ray1016/Colmar-Academy/blob/master/resources/css/style.css#L221-L223

You also have an empty block on this line: https://github.com/Ray1016/Colmar-Academy/blob/master/resources/css/style.css#L335

**Comment by rayaffas** [comment]
Fixed with this commit [583b246](https://github.com/Ray1016/Colmar-Academy/commit/58fcbb78701c3f2437985859de35f1f55583b246)
