### ISSUE TITLE
Hover effect

### ISSUE THREAD

**Issue by carodelafuente** [Ray1016/Colmar-Academy#4]
It's good to note user experience when implementing something like a hover feature. You used hover on your mobile media queries-- but can you really _hover_ over something on a mobile screen? Maybe it's best to use hover for desktop styles. Just something to think about.

**Comment by rayaffas** [comment]
_Hover_ is only implemented in desktop styles. It is inherited by default to mobile size styles and I didn't want to disable them considering that the user might resize the browser when using a desktop or a laptop.
